data_dir = "/home/oliverr/ygramul/data"

[neo4j]
uri = "54.197.200.223"
user = "neo4j"

[pigean]
data_dir = "s3://dig-analysis-data/out/pigean/staging/pigean/portal/"
sub_dir = "cfde"
factors_dir = "s3://psmadbec-test/backup/old-pigean/factor/sigma=2/size=small/portal/"
pheno_names = "pigean-phenotypes.csv"
